sudo: required
services: 
  - docker

before_install:
  - docker build -t gosho300/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gosho300/react-test npm test

after_success:
  - docker build -t gosho300/multi-client ./client
  - docker build -t gosho300/multi-nginx ./nginx
  - docker build -t gosho300/multi-server ./server
  - docker build -t gosho300/multi-worker ./worker

  #Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push gosho300/multi-client
  - docker push gosho300/multi-nginx
  - docker push gosho300/multi-server
  - docker push gosho300/multi-worker